/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_diegomatamoros;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Family
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        bt_iniciar = new javax.swing.JButton();
        bt_crear = new javax.swing.JButton();
        jt_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Contraseña");

        jt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_usuarioActionPerformed(evt);
            }
        });

        bt_iniciar.setText("Iniciar Sesion");
        bt_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarMouseClicked(evt);
            }
        });

        bt_crear.setText("Crear");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
        });
        bt_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_iniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_crear)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(bt_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(bt_crear)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crearActionPerformed

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        AñadirUsuario añadir = new AñadirUsuario();
        añadir.setVisible(true);
    }//GEN-LAST:event_bt_crearMouseClicked

    private void jt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_usuarioActionPerformed

    }//GEN-LAST:event_jt_usuarioActionPerformed
    static int r;
    private void bt_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarMouseClicked
        AñadirUsuario u = new AñadirUsuario();
        u.lista.add(new Usuarios("Salvador", "Nasralla", "99999999", "dam_900@hotmail.com", "ElMeroPresi", "historia", new Date()));
        for (int i = 0; i < u.lista.size(); i++) {
            if ("Salvador".equals(jt_usuario.getText())) {
                if ("Nasralla".equals(jt_pass.getText())) {
                    int menu;
                    do {

                        Usuarios l = new Libros();
                        menu = Integer.parseInt(JOptionPane.showInputDialog("1.Agregar Libros\n2.Modificar Libros\n3.Eliminar Libros\n 0.Salir"));
                        if (menu == 1) {
                            String titulo, descripcion, genero, autor;
                            int copias, puntaje, añoPublicacion, valor, edicion;
                            titulo = JOptionPane.showInputDialog("Introduzca un titulo para el libro");
                            descripcion = JOptionPane.showInputDialog("Introduzca un descripcion");
                            genero = JOptionPane.showInputDialog("Introduzca una descripcion");
                            autor = JOptionPane.showInputDialog("Introduzca un genero");
                            copias = Integer.parseInt(JOptionPane.showInputDialog("Introduzca las copias"));
                            puntaje = Integer.parseInt(JOptionPane.showInputDialog("Introducir puntaje"));
                            añoPublicacion = Integer.parseInt(JOptionPane.showInputDialog("Introducir año de publicacion"));
                            valor = Integer.parseInt(JOptionPane.showInputDialog("Introduzca un valor"));
                            edicion = Integer.parseInt(JOptionPane.showInputDialog("Introduzca una edicion"));
                            l.libros.add(new Libros(titulo, descripcion, genero, autor, copias, puntaje, añoPublicacion, valor, edicion));

                        }
                        if (menu == 2) {
                            String suma = "";
                            for (int j = 0; j < l.libros.size(); j++) {
                                suma += "-" + l.libros.get(j) + "\n";
                            }
                            int menu2 = Integer.parseInt("Su lista:\n" + JOptionPane.showInputDialog(suma));
                            String titulo, descripcion, genero, autor;
                            int copias, puntaje, añoPublicacion, valor, edicion;
                            titulo = JOptionPane.showInputDialog("Introduzca un titulo para el libro");
                            descripcion = JOptionPane.showInputDialog("Introduzca un descripcion");
                            genero = JOptionPane.showInputDialog("Introduzca una descripcion");
                            autor = JOptionPane.showInputDialog("Introduzca un genero");
                            copias = Integer.parseInt(JOptionPane.showInputDialog("Introduzca las copias"));
                            puntaje = Integer.parseInt(JOptionPane.showInputDialog("Introducir puntaje"));
                            añoPublicacion = Integer.parseInt(JOptionPane.showInputDialog("Introducir año de publicacion"));
                            valor = Integer.parseInt(JOptionPane.showInputDialog("Introduzca un valor"));
                            edicion = Integer.parseInt(JOptionPane.showInputDialog("Introduzca una edicion"));
                            l.libros.set(menu2, new Libros(titulo, descripcion, genero, autor, copias, puntaje, añoPublicacion, valor, edicion));
                        }
                        if (menu==3) {
                            String suma2 = null;
                            for (int j = 0; j < l.libros.size(); j++) {
                                suma2 += "-" + l.libros.get(j) + "\n";
                            }
                            int menu2 = Integer.parseInt("Cualquiere eliminar-Su lista:\n" + JOptionPane.showInputDialog(suma2));
                            l.libros.remove(menu2);
                        }
                    } while (menu != 0);

                }
            }
            if (u.lista.get(i).getNombre().equals(jt_usuario.getText()) && !"Salvador".equals(jt_usuario.getText())) {
                if (u.lista.get(i).getContraseña().equals(jt_pass.getText()) && !"Salvador".equals(jt_usuario.getText())) {
                    r = i;
                    Main m = new Main();
                    m.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ha introducido mal la contraseña");
                }
            }
        }
    }//GEN-LAST:event_bt_iniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login().setVisible(true);
            }
        });
    }

    public int devolver() {
        return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jt_pass;
    private javax.swing.JTextField jt_usuario;
    // End of variables declaration//GEN-END:variables
}
