/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_diegomatamoros;

import java.util.EmptyStackException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Family
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Puntaje = new javax.swing.JLabel();
        Copias = new javax.swing.JLabel();
        Genero = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Autos = new javax.swing.JLabel();
        Año = new javax.swing.JLabel();
        jt_titulo = new javax.swing.JTextField();
        jt_descripcion = new javax.swing.JTextField();
        jt_puntaje = new javax.swing.JTextField();
        jt_copias = new javax.swing.JTextField();
        jt_genero = new javax.swing.JTextField();
        jt_valor = new javax.swing.JTextField();
        jt_edicion = new javax.swing.JTextField();
        jt_autos = new javax.swing.JTextField();
        jt_añoPubli = new javax.swing.JTextField();
        jb_añadir = new javax.swing.JButton();
        jt_volver = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jt_añadir = new javax.swing.JButton();
        jt_actualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cb_solicitud = new javax.swing.JComboBox<>();
        jt_agregar = new javax.swing.JButton();
        jb_acut = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cb_libros = new javax.swing.JComboBox<>();
        jb_actualizar = new javax.swing.JButton();
        jb_devolver = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_historial = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Añadir Libros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Titulo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Descripcion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Puntaje.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Puntaje.setForeground(new java.awt.Color(0, 255, 255));
        Puntaje.setText("Puntaje");
        jPanel1.add(Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        Copias.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Copias.setForeground(new java.awt.Color(0, 255, 255));
        Copias.setText("CopiasDisponibles");
        jPanel1.add(Copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        Genero.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Genero.setForeground(new java.awt.Color(0, 255, 255));
        Genero.setText("Genero");
        jPanel1.add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, -1));

        Valor.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(0, 204, 204));
        Valor.setText("Valor");
        jPanel1.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Edicion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        Autos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Autos.setForeground(new java.awt.Color(0, 204, 204));
        Autos.setText("Autos");
        jPanel1.add(Autos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        Año.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Año.setForeground(new java.awt.Color(0, 255, 255));
        Año.setText("AñoPublicacion");
        jPanel1.add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));
        jPanel1.add(jt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 90, -1));
        jPanel1.add(jt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 50));
        jPanel1.add(jt_puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 100, -1));
        jPanel1.add(jt_copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, -1));
        jPanel1.add(jt_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 80, -1));
        jPanel1.add(jt_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 80, -1));
        jPanel1.add(jt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 80, -1));
        jPanel1.add(jt_autos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 100, -1));
        jPanel1.add(jt_añoPubli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 70, -1));

        jb_añadir.setText("AÑADIR");
        jb_añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_añadirMouseClicked(evt);
            }
        });
        jb_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_añadirActionPerformed(evt);
            }
        });
        jPanel1.add(jb_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jt_volver.setText("Volver");
        jt_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_volverMouseClicked(evt);
            }
        });
        jt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_volverActionPerformed(evt);
            }
        });
        jPanel1.add(jt_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen1_diegomatamoros/biblioteca_libros_prohibidos.jpg"))); // NOI18N
        jPanel1.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        jTabbedPane1.addTab("Añadir Libros", jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Añadir amigos");

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jt_añadir.setText("AÑADIR");
        jt_añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_añadirMouseClicked(evt);
            }
        });
        jt_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_añadirActionPerformed(evt);
            }
        });

        jt_actualizar.setText("Actualizar");
        jt_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_actualizarMouseClicked(evt);
            }
        });
        jt_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_actualizarActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jt_añadir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jt_actualizar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_añadir))
                .addGap(38, 38, 38)
                .addComponent(jt_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Añadir Amigos", jPanel2);

        cb_solicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_solicitudActionPerformed(evt);
            }
        });

        jt_agregar.setText("AGREGAR");
        jt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_agregarMouseClicked(evt);
            }
        });

        jb_acut.setText("Actualizar");
        jb_acut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_acutActionPerformed(evt);
            }
        });
        jb_acut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_acutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(cb_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jt_agregar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jb_acut)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_agregar))
                .addGap(18, 18, 18)
                .addComponent(jb_acut)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Solicitudes", jPanel4);

        cb_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_librosActionPerformed(evt);
            }
        });

        jb_actualizar.setText("Actualizar");
        jb_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarActionPerformed(evt);
            }
        });

        jb_devolver.setText("Devolver");
        jb_devolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_devolverMouseClicked(evt);
            }
        });
        jb_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_devolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cb_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jb_actualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 287, Short.MAX_VALUE)
                .addComponent(jb_devolver)
                .addGap(233, 233, 233))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(cb_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jb_devolver)
                .addGap(24, 24, 24)
                .addComponent(jb_actualizar)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mostrar Libros", jPanel3);

        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_actualizarMouseClicked(evt);
            }
        });
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jl_historial);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Historial");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton_actualizar)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton_actualizar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_añadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_añadirActionPerformed

    private void jb_añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_añadirMouseClicked
        Usuarios u = new Usuarios();
        Usuarios.historial.add("Se ha agregado un libro");
        AñadirUsuario a = new AñadirUsuario();
        Login l = new Login();
        try {
            String titulo, descripcion, genero, autor;
            int copias, puntaje, añoPublicacion, valor, edicion;
            titulo = jt_titulo.getText();
            descripcion = jt_descripcion.getText();
            genero = jt_genero.getText();
            if (genero.toLowerCase().equals("fantasia")) {
                genero = "fantasia";
            }
            if (genero.toLowerCase().equals("romance")) {
                genero = "romance";
            }
            if (genero.toLowerCase().equals("accion")) {
                genero = "accion";
            }
            if (genero.toLowerCase().equals("historia")) {
                genero = "historia";
            }
            if (!genero.toLowerCase().equals("fantasia") && !genero.toLowerCase().equals("romance") && !genero.toLowerCase().equals("accion") && !genero.toLowerCase().equals("historia")) {
                throw new EmptyStackException();
            }
            autor = this.jt_autos.getText();
            copias = Integer.parseInt(this.jt_copias.getText());
            puntaje = Integer.parseInt(this.jt_puntaje.getText());
            añoPublicacion = Integer.parseInt(this.jt_añoPubli.getText());
            valor = Integer.parseInt(this.jt_valor.getText());
            edicion = Integer.parseInt(this.jt_edicion.getText());
            u.libros.add(new Libros(titulo, descripcion, genero, autor,
                    copias, puntaje, añoPublicacion, valor, edicion));
            jt_autos.setText("");
            jt_titulo.setText("");
            jt_descripcion.setText("");
            jt_genero.setText("");
            jt_copias.setText("");
            jt_puntaje.setText("");
            jt_añoPubli.setText("");
            jt_valor.setText("");
            jt_edicion.setText("");
            JOptionPane.showMessageDialog(this, "se ha añadido exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ha introducido mal algo");
        }


    }//GEN-LAST:event_jb_añadirMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_volverActionPerformed
        Login l = new Login();
        Usuarios.historial.add("se ha regresado al login");
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jt_volverActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jt_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_actualizarMouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox1.getModel();
        Usuarios.historial.add("Actualizar lista de amigos");
        AñadirUsuario u = new AñadirUsuario();
        Login l = new Login();
        modelo.removeAllElements();
        for (int i = 0; i < u.lista.size(); i++) {
            if (l.nombre().equals(u.lista.get(i).getNombre())) {
            } else {
                modelo.addElement(u.lista.get(i).getNombre());
            }

        }
    }//GEN-LAST:event_jt_actualizarMouseClicked

    private void jt_añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_añadirMouseClicked
        Usuarios r = new Usuarios();
        Usuarios.historial.add("Se ha enviado una solicitud");
        Login l=new Login();
        Usuarios.Amiguitos.add(jComboBox1.getSelectedItem().toString());
        Usuarios.solicitud.add(new Solicitude(l.nombre(),jComboBox1.getSelectedItem().toString()));

    }//GEN-LAST:event_jt_añadirMouseClicked

    private void cb_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_librosActionPerformed
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros.getModel();
        AñadirUsuario u = new AñadirUsuario();
        Usuarios s = new Usuarios();
        modelo.removeAllElements();
        for (int i = 0; i < s.libros.size(); i++) {

            modelo.addElement(s.libros.get(i).getTitulo());

        }

    }//GEN-LAST:event_cb_librosActionPerformed

    private void jb_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_devolverActionPerformed
        Usuarios s = new Usuarios();
        s.historial.add("Se ha devuelto un libro");
        int pos = cb_libros.getSelectedIndex();
        s.libros.remove(pos);
    }//GEN-LAST:event_jb_devolverActionPerformed

    private void jb_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarActionPerformed

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros.getModel();
        modelo.removeAllElements();
        AñadirUsuario u = new AñadirUsuario();
        Usuarios s = new Usuarios();
        modelo.removeAllElements();
        for (int i = 0; i < s.libros.size(); i++) {

            modelo.addElement(s.libros.get(i).getTitulo());

        }
    }//GEN-LAST:event_jb_actualizarActionPerformed

    private void jb_acutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_acutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_acutActionPerformed

    private void jt_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_actualizarActionPerformed

    private void jt_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_añadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_añadirActionPerformed

    private void jb_acutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_acutKeyPressed
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_solicitud.getModel();
        AñadirUsuario u = new AñadirUsuario();
        
        Login l=new Login();
        modelo.removeAllElements();
        for (int i = 0; i <Usuarios.solicitud.size(); i++) {
            if (Usuarios.solicitud.get(i).aQuien.equals(l.nombre())) {
                modelo.addElement(Usuarios.solicitud.get(i).nombre);
            }
            

        }
    }//GEN-LAST:event_jb_acutKeyPressed

    private void jt_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_volverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_volverMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_solicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_solicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_solicitudActionPerformed

    private void jt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_agregarMouseClicked
       Usuarios.historial.add("Se ha agregado al amigo");
    }//GEN-LAST:event_jt_agregarMouseClicked

    private void jb_devolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_devolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_devolverMouseClicked

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_actualizarMouseClicked
        DefaultListModel listModel=new DefaultListModel();
        for (int i = 0; i < Usuarios.historial.size(); i++) {
            listModel.addElement(Usuarios.historial.get(i));
        }
        jl_historial.setModel(listModel);
    }//GEN-LAST:event_jButton_actualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autos;
    private javax.swing.JLabel Año;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Copias;
    private javax.swing.JLabel Genero;
    private javax.swing.JLabel Puntaje;
    private javax.swing.JLabel Valor;
    private javax.swing.JComboBox<String> cb_libros;
    private javax.swing.JComboBox<String> cb_solicitud;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_acut;
    private javax.swing.JButton jb_añadir;
    private javax.swing.JButton jb_devolver;
    private javax.swing.JList<String> jl_historial;
    private javax.swing.JButton jt_actualizar;
    private javax.swing.JButton jt_agregar;
    private javax.swing.JTextField jt_autos;
    private javax.swing.JButton jt_añadir;
    private javax.swing.JTextField jt_añoPubli;
    private javax.swing.JTextField jt_copias;
    private javax.swing.JTextField jt_descripcion;
    private javax.swing.JTextField jt_edicion;
    private javax.swing.JTextField jt_genero;
    private javax.swing.JTextField jt_puntaje;
    private javax.swing.JTextField jt_titulo;
    private javax.swing.JTextField jt_valor;
    private javax.swing.JButton jt_volver;
    // End of variables declaration//GEN-END:variables
}
